---
title: "flexdashboard: Shiny Embedding"
output: 
  flexdashboard::flex_dashboard:
    social: menu
    source_code: embed 
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(shinydashboard)
library(dplyr)
source("gapModule_flexdashboard.R")
source("data.R")
source("boxvalue_module.R")
source("infobox_module.R")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
worldPhonesUI("all")
callModule(worldPhones, "all", all_data)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
worldPhonesUI("europe")
callModule(worldPhones, "europe", europe_data)
```

### Chart C

```{r}
worldPhonesUI("americas")
callModule(worldPhones, "americas", americas_data)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart D

```{r}
iboxesUI("americas_box")
callModule(iboxes, "americas_box", data = 0.5555)
```

### Chart E

```{r}
iboxesUI("americas_box2")
callModule(iboxes, "americas_box2", data = 0.8)

```

### Chart F

```{r}
iboxesUI("americas_box3")
callModule(iboxes, "americas_box3", data = 5)

```

### Chart G

```{r}
iboxesUI("luigi")
callModule(iboxes, "luigi", data = 5)

```

### Chart H

```{r}
infoboxesUI("ciao")
callModule(infoboxes, "ciao", data = 5)

```

### Chart I

```{r}
infoboxesUI("ciao2")
callModule(infoboxes, "ciao2", data = 555)

```

